In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("hotel_booking.csv")

In [9]:
df.shape

(119390, 36)

In [8]:
print(df.head())

          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July
1  Resort Hotel            0        737               2015               July
2  Resort Hotel            0          7               2015               July
3  Resort Hotel            0         13               2015               July
4  Resort Hotel            0         14               2015               July

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1
1                        27                          1
2                        27                          1
3                        27                          1
4                        27                          1

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  customer_type  \
0                        0                     0       2  ...      Transient
1                        0                     0       2  ...      Transient
2                        0                     1       1  ...      Transient
3                        0                     1       1  ...      Transient
4                        0                     2       2  ...      Transient

    adr required_car_parking_spaces total_of_special_requests  \
0   0.0                           0                         0
1   0.0                           0                         0
2  75.0                           0                         0
3  75.0                           0                         0
4  98.0                           0                         1

  reservation_status reservation_status_date            name  \
0          Check-Out              2015-07-01   Ernest Barnes
1          Check-Out              2015-07-01    Andrea Baker
2          Check-Out              2015-07-02  Rebecca Parker
3          Check-Out              2015-07-02    Laura Murray
4          Check-Out              2015-07-03     Linda Hines

                         email  phone-number       credit_card
0  Ernest.Barnes31@outlook.com  669-792-1661  ************4322
1       Andrea_Baker94@aol.com  858-637-6955  ************9157
2   Rebecca_Parker@comcast.net  652-885-2745  ************3734
3            Laura_M@gmail.com  364-656-8427  ************5677
4           LHines@verizon.com  713-226-5883  ************5498

[5 rows x 36 columns]

In [43]:
df.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
name                                0
email                               0
phone-number                        0
credit_card                         0
dtype: int64

In [40]:
df = df.drop(['agent','company'], axis=1)

In [45]:
df = df.dropna()

In [46]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
name                              0
email                             0
phone-number                      0
credit_card                       0
dtype: int64

In [52]:
df = df.rename(columns = {'stays_in_weekend_nights' : 'num_of_weekend_nights', 'stays_in_week_nights' : 'num_of_week_nights', 'adr' : 'average_daily_rate'})

In [53]:
print(df.head(5))

          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July
1  Resort Hotel            0        737               2015               July
2  Resort Hotel            0          7               2015               July
3  Resort Hotel            0         13               2015               July
4  Resort Hotel            0         14               2015               July

   arrival_date_week_number  arrival_date_day_of_month  num_of_weekend_nights  \
0                        27                          1                      0
1                        27                          1                      0
2                        27                          1                      0
3                        27                          1                      0
4                        27                          1                      0

   num_of_week_nights  adults  ...  customer_type  average_daily_rate  \
0                   0       2  ...      Transient                 0.0
1                   0       2  ...      Transient                 0.0
2                   1       1  ...      Transient                75.0
3                   1       1  ...      Transient                75.0
4                   2       2  ...      Transient                98.0

  required_car_parking_spaces total_of_special_requests reservation_status  \
0                           0                         0          Check-Out
1                           0                         0          Check-Out
2                           0                         0          Check-Out
3                           0                         0          Check-Out
4                           0                         1          Check-Out

  reservation_status_date            name                        email  \
0              2015-07-01   Ernest Barnes  Ernest.Barnes31@outlook.com
1              2015-07-01    Andrea Baker       Andrea_Baker94@aol.com
2              2015-07-02  Rebecca Parker   Rebecca_Parker@comcast.net
3              2015-07-02    Laura Murray            Laura_M@gmail.com
4              2015-07-03     Linda Hines           LHines@verizon.com

   phone-number       credit_card
0  669-792-1661  ************4322
1  858-637-6955  ************9157
2  652-885-2745  ************3734
3  364-656-8427  ************5677
4  713-226-5883  ************5498

[5 rows x 34 columns]

In [55]:
df['arrival_date_year'] = df['arrival_date_year'].astype(str)
df['arrival_date_month'] = df['arrival_date_month'].astype(str)
df['arrival_date_day_of_month'] = df['arrival_date_day_of_month'].astype(str)

In [56]:
df['arrival_date'] = df['arrival_date_year'] + '-' + df['arrival_date_month'] + '-' + df['arrival_date_day_of_month']

In [57]:
df['arrival_date'] = pd.to_datetime(df['arrival_date'])

In [59]:
df.drop(['arrival_date_year','arrival_date_month','arrival_date_day_of_month'],axis=1)

,hotel,is_canceled,lead_time,arrival_date_week_number,num_of_weekend_nights,num_of_week_nights,adults,children,babies,meal,...,average_daily_rate,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,arrival_date
0,Resort Hotel,0,342,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,2015-07-01
1,Resort Hotel,0,737,27,0,0,2,0.0,0,BB,...,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2015-07-01
2,Resort Hotel,0,7,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,2015-07-01
3,Resort Hotel,0,13,27,0,1,1,0.0,0,BB,...,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,2015-07-01
4,Resort Hotel,0,14,27,0,2,2,0.0,0,BB,...,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0.0,0,BB,...,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647,2017-08-30
119386,City Hotel,0,102,35,2,5,3,0.0,0,BB,...,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333,2017-08-31
119387,City Hotel,0,34,35,2,5,2,0.0,0,BB,...,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821,2017-08-31
119388,City Hotel,0,109,35,2,5,2,0.0,0,BB,...,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860,2017-08-31
119389,City Hotel,0,205,35,2,7,2,0.0,0,HB,...,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482,2017-08-29

In [60]:
df = df[['name','email','phone-number','credit_card','arrival_date','reservation_status_date','reservation_status'] + list(df.columns[:-8])]

In [61]:
print(df.head(5))

             name                        email  phone-number  \
0   Ernest Barnes  Ernest.Barnes31@outlook.com  669-792-1661
1    Andrea Baker       Andrea_Baker94@aol.com  858-637-6955
2  Rebecca Parker   Rebecca_Parker@comcast.net  652-885-2745
3    Laura Murray            Laura_M@gmail.com  364-656-8427
4     Linda Hines           LHines@verizon.com  713-226-5883

        credit_card arrival_date reservation_status_date reservation_status  \
0  ************4322   2015-07-01              2015-07-01          Check-Out
1  ************9157   2015-07-01              2015-07-01          Check-Out
2  ************3734   2015-07-01              2015-07-02          Check-Out
3  ************5677   2015-07-01              2015-07-02          Check-Out
4  ************5498   2015-07-01              2015-07-03          Check-Out

          hotel  is_canceled  lead_time  ... previous_cancellations  \
0  Resort Hotel            0        342  ...                      0
1  Resort Hotel            0        737  ...                      0
2  Resort Hotel            0          7  ...                      0
3  Resort Hotel            0         13  ...                      0
4  Resort Hotel            0         14  ...                      0

  previous_bookings_not_canceled  reserved_room_type assigned_room_type  \
0                              0                   C                  C
1                              0                   C                  C
2                              0                   A                  C
3                              0                   A                  A
4                              0                   A                  A

   booking_changes  deposit_type  days_in_waiting_list  customer_type  \
0                3    No Deposit                     0      Transient
1                4    No Deposit                     0      Transient
2                0    No Deposit                     0      Transient
3                0    No Deposit                     0      Transient
4                0    No Deposit                     0      Transient

   average_daily_rate required_car_parking_spaces
0                 0.0                           0
1                 0.0                           0
2                75.0                           0
3                75.0                           0
4                98.0                           0

[5 rows x 34 columns]

In [62]:
df['is_canceled'] = df['is_canceled'].astype(bool)
df['is_repeated_guest'] = df['is_repeated_guest'].astype(bool)

In [63]:
print(df['is_canceled'])

0         False
1         False
2         False
3         False
4         False
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Name: is_canceled, Length: 118898, dtype: bool

In [64]:
duplicates = df[df.duplicated()]

print(duplicates)

Empty DataFrame
Columns: [name, email, phone-number, credit_card, arrival_date, reservation_status_date, reservation_status, hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, num_of_weekend_nights, num_of_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, days_in_waiting_list, customer_type, average_daily_rate, required_car_parking_spaces]
Index: []

[0 rows x 34 columns]

In [65]:
df['children'] = df['children'].astype(int)

In [66]:
df['average_daily_rate'] = '$' + df['average_daily_rate'].astype(float).round(2).astype(str)

In [67]:
df.drop(['arrival_date_week_number'],axis=1)

,name,email,phone-number,credit_card,arrival_date,reservation_status_date,reservation_status,hotel,is_canceled,lead_time,...,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,average_daily_rate,required_car_parking_spaces
0,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,2015-07-01,2015-07-01,Check-Out,Resort Hotel,False,342,...,0,0,C,C,3,No Deposit,0,Transient,$0.0,0
1,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,2015-07-01,2015-07-01,Check-Out,Resort Hotel,False,737,...,0,0,C,C,4,No Deposit,0,Transient,$0.0,0
2,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734,2015-07-01,2015-07-02,Check-Out,Resort Hotel,False,7,...,0,0,A,C,0,No Deposit,0,Transient,$75.0,0
3,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677,2015-07-01,2015-07-02,Check-Out,Resort Hotel,False,13,...,0,0,A,A,0,No Deposit,0,Transient,$75.0,0
4,Linda Hines,LHines@verizon.com,713-226-5883,************5498,2015-07-01,2015-07-03,Check-Out,Resort Hotel,False,14,...,0,0,A,A,0,No Deposit,0,Transient,$98.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647,2017-08-30,2017-09-06,Check-Out,City Hotel,False,23,...,0,0,A,A,0,No Deposit,0,Transient,$96.14,0
119386,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333,2017-08-31,2017-09-07,Check-Out,City Hotel,False,102,...,0,0,E,E,0,No Deposit,0,Transient,$225.43,0
119387,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821,2017-08-31,2017-09-07,Check-Out,City Hotel,False,34,...,0,0,D,D,0,No Deposit,0,Transient,$157.71,0
119388,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860,2017-08-31,2017-09-07,Check-Out,City Hotel,False,109,...,0,0,A,A,0,No Deposit,0,Transient,$104.4,0
119389,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482,2017-08-29,2017-09-07,Check-Out,City Hotel,False,205,...,0,0,A,A,0,No Deposit,0,Transient,$151.2,0

In [68]:
df.to_csv('cleaned_data.csv')